# Claude AI Provider Configuration
# Settings specific to Anthropic's Claude API

provider:
  name: "claude"
  display_name: "Claude 3 Opus"
  api_base_url: "https://api.anthropic.com/v1"
  
models:
  default: "claude-3-opus-20240229"
  available:
    - name: "claude-3-opus-20240229"
      max_tokens: 4096
      supports_vision: true
      cost_per_1k_input: 0.015
      cost_per_1k_output: 0.075
      
    - name: "claude-3-sonnet-20240229"
      max_tokens: 4096
      supports_vision: true
      cost_per_1k_input: 0.003
      cost_per_1k_output: 0.015
      
    - name: "claude-3-haiku-20240307"
      max_tokens: 4096
      supports_vision: true
      cost_per_1k_input: 0.00025
      cost_per_1k_output: 0.00125

# Request parameters
request_params:
  temperature: 0.2  # Lower for consistent code generation
  max_tokens: 4096
  top_p: 0.95
  stop_sequences: []
  
# Rate limiting
rate_limits:
  requests_per_minute: 50
  tokens_per_minute: 40000
  concurrent_requests: 5
  
# Retry configuration
retry:
  max_attempts: 3
  initial_delay: 1
  max_delay: 10
  exponential_base: 2
  
# Special features
features:
  supports_system_prompt: true
  supports_function_calling: true
  supports_vision: true
  supports_streaming: true
  max_context_window: 200000
  
# Headers
headers:
  anthropic-version: "2023-06-01"
  content-type: "application/json"
  
# Error handling
error_messages:
  rate_limit: "Rate limit exceeded. Waiting before retry..."
  api_error: "Claude API error occurred"
  timeout: "Request timed out"
  invalid_key: "Invalid API key"