version: '3.8'

services:
  autoplaytest:
    build: .
    container_name: autoplaytest
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_URL=postgresql://postgres:password@db:5432/autoplaytest
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./generated_tests:/app/generated_tests
    depends_on:
      - db
      - redis
    networks:
      - autoplaytest-network

  db:
    image: postgres:15-alpine
    container_name: autoplaytest-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=autoplaytest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - autoplaytest-network

  redis:
    image: redis:7-alpine
    container_name: autoplaytest-redis
    ports:
      - "6379:6379"
    networks:
      - autoplaytest-network

  nginx:
    image: nginx:alpine
    container_name: autoplaytest-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - autoplaytest
    networks:
      - autoplaytest-network

volumes:
  postgres_data:

networks:
  autoplaytest-network:
    driver: bridge